export type LegalLocale = 'de' | 'en' | 'et' | 'es' | 'fr' | 'it' | 'lv' | 'lt' | 'nl' | 'pl' | 'pt' | 'fi' | 'sv' | 'uk' | 'ru';

type LegalSection = {
  title: string;
  paragraphs: string[];
};

type LegalDoc = {
  updated: string;
  sections: LegalSection[];
};

export const TERMS_CONTENT: Record<LegalLocale, LegalDoc> = {
  en: {
    updated: 'Last updated: February 15, 2026',
    sections: [
      { title: '1. Operator', paragraphs: ['Rootwise is operated by EventNexus OÜ (reg. no. 17431557), Põltsamaa, Estonia.', 'Contact: villu@mail.eventnexus.eu', 'Website: www.eventnexus.eu'] },
      { title: '2. Acceptance of Terms', paragraphs: ['By creating an account or using Rootwise, you agree to these Terms and applicable laws. If you do not agree, do not use the service.'] },
      { title: '3. Accounts & Eligibility', paragraphs: ['You are responsible for account accuracy and account security. You must not impersonate others or use the platform for unlawful or abusive purposes.'] },
      { title: '4. Acceptable Use', paragraphs: ['You agree not to post harmful, illegal, infringing, or abusive content; attempt unauthorized access; or interfere with platform integrity, availability, or other users.'] },
      { title: '5. User Content', paragraphs: ['You retain ownership of content you upload. By posting content, you grant Rootwise a limited license to host, display, and process that content for platform operation.'] },
      { title: '6. Paid Features & Billing', paragraphs: ['Some functionality is available through paid plans. Billing, renewals, and cancellations are managed via the payment provider flow shown in the app.'] },
      { title: '7. Suspension & Termination', paragraphs: ['We may suspend or terminate accounts that violate these Terms, harm users, or create security/legal risks.'] },
      { title: '8. Disclaimer & Liability', paragraphs: ['The service is provided on an "as is" and "as available" basis. To the maximum extent permitted by law, EventNexus OÜ is not liable for indirect, incidental, or consequential damages.'] },
      { title: '9. Changes to Terms', paragraphs: ['We may update these Terms from time to time. Updated versions are effective upon publication, with the updated date shown on this page.'] },
      { title: '10. Contact', paragraphs: ['Questions about these Terms can be sent to villu@mail.eventnexus.eu. Typical response time: within 24 hours.'] },
    ],
  },
  et: {
    updated: 'Viimati uuendatud: 15. veebruar 2026',
    sections: [
      { title: '1. Teenusepakkuja', paragraphs: ['Rootwise teenust haldab EventNexus OÜ (reg. nr 17431557), Põltsamaa, Eesti.', 'Kontakt: villu@mail.eventnexus.eu', 'Veeb: www.eventnexus.eu'] },
      { title: '2. Tingimustega nõustumine', paragraphs: ['Konto loomisel või Rootwise kasutamisel nõustud nende tingimuste ja kohaldatavate seadustega. Kui sa ei nõustu, ära teenust kasuta.'] },
      { title: '3. Kontod ja sobivus', paragraphs: ['Vastutad kontoandmete õigsuse ja konto turvalisuse eest. Teiste kehastamine ning ebaseaduslik või kuritarvitav kasutus ei ole lubatud.'] },
      { title: '4. Lubatud kasutus', paragraphs: ['Sa ei tohi postitada kahjulikku, ebaseaduslikku, õigusi rikkuvat või kuritarvitavat sisu, proovida volitamata ligipääsu ega häirida platvormi toimimist või teisi kasutajaid.'] },
      { title: '5. Kasutajasisu', paragraphs: ['Säilitad üleslaaditud sisu omandiõiguse. Sisu avaldamisel annad Rootwise’ile piiratud õiguse seda platvormi toimimiseks majutada, kuvada ja töödelda.'] },
      { title: '6. Tasulised funktsioonid ja arveldus', paragraphs: ['Osa funktsioone on saadaval tasulistes pakettides. Arveldus, uuendused ja tühistamised toimuvad rakenduses kuvatava makselahenduse kaudu.'] },
      { title: '7. Peatamine ja lõpetamine', paragraphs: ['Võime peatada või lõpetada kontosid, mis rikuvad tingimusi, kahjustavad kasutajaid või loovad turva- või õigusriske.'] },
      { title: '8. Vastutusest loobumine ja vastutus', paragraphs: ['Teenust pakutakse põhimõttel „nagu on“ ja „vastavalt saadavusele“. Seadusega lubatud ulatuses ei vastuta EventNexus OÜ kaudsete või kaasnevate kahjude eest.'] },
      { title: '9. Tingimuste muutmine', paragraphs: ['Võime neid tingimusi aeg-ajalt uuendada. Uus versioon jõustub avaldamisel ning selle kuupäev kuvatakse sellel lehel.'] },
      { title: '10. Kontakt', paragraphs: ['Küsimused tingimuste kohta saada aadressile villu@mail.eventnexus.eu. Tavapärane vastamisaeg: kuni 24 tundi.'] },
    ],
  },
  de: {
    updated: 'Zuletzt aktualisiert: 15. Februar 2026',
    sections: [
      { title: '1. Betreiber', paragraphs: ['Rootwise wird von EventNexus OÜ (Reg.-Nr. 17431557), Põltsamaa, Estland, betrieben.', 'Kontakt: villu@mail.eventnexus.eu', 'Webseite: www.eventnexus.eu'] },
      { title: '2. Annahme der Bedingungen', paragraphs: ['Durch die Erstellung eines Kontos oder die Nutzung von Rootwise stimmen Sie diesen Bedingungen und den geltenden Gesetzen zu. Wenn Sie nicht zustimmen, nutzen Sie den Dienst nicht.'] },
      { title: '3. Konten und Berechtigung', paragraphs: ['Sie sind für die Richtigkeit Ihrer Kontodaten und die Sicherheit Ihres Kontos verantwortlich. Das Vortäuschen einer anderen Person sowie rechtswidrige oder missbräuchliche Nutzung sind untersagt.'] },
      { title: '4. Zulässige Nutzung', paragraphs: ['Sie verpflichten sich, keine schädlichen, rechtswidrigen, verletzenden oder missbräuchlichen Inhalte zu veröffentlichen, keinen unbefugten Zugriff zu versuchen und die Plattform oder andere Nutzer nicht zu beeinträchtigen.'] },
      { title: '5. Nutzerinhalte', paragraphs: ['Sie behalten das Eigentum an Ihren hochgeladenen Inhalten. Mit der Veröffentlichung räumen Sie Rootwise eine beschränkte Lizenz ein, Inhalte für den Betrieb der Plattform zu hosten, anzuzeigen und zu verarbeiten.'] },
      { title: '6. Bezahlte Funktionen und Abrechnung', paragraphs: ['Einige Funktionen sind über kostenpflichtige Pläne verfügbar. Abrechnung, Verlängerung und Kündigung erfolgen über den im Produkt angezeigten Zahlungsablauf.'] },
      { title: '7. Sperrung und Kündigung', paragraphs: ['Wir können Konten sperren oder kündigen, die gegen diese Bedingungen verstoßen, Nutzer schädigen oder Sicherheits- bzw. Rechtsrisiken verursachen.'] },
      { title: '8. Haftungsausschluss und Haftung', paragraphs: ['Der Dienst wird „wie besehen“ und „wie verfügbar“ bereitgestellt. Soweit gesetzlich zulässig, haftet EventNexus OÜ nicht für mittelbare oder Folgeschäden.'] },
      { title: '9. Änderungen der Bedingungen', paragraphs: ['Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Aktualisierte Fassungen gelten mit Veröffentlichung; das Datum der letzten Aktualisierung steht auf dieser Seite.'] },
      { title: '10. Kontakt', paragraphs: ['Fragen zu diesen Bedingungen senden Sie bitte an villu@mail.eventnexus.eu. Übliche Antwortzeit: innerhalb von 24 Stunden.'] },
    ],
  },
  es: {
    updated: 'Última actualización: 15 de febrero de 2026',
    sections: [
      { title: '1. Operador', paragraphs: ['Rootwise es operado por EventNexus OÜ (n.º de registro 17431557), Põltsamaa, Estonia.', 'Contacto: villu@mail.eventnexus.eu', 'Sitio web: www.eventnexus.eu'] },
      { title: '2. Aceptación de los términos', paragraphs: ['Al crear una cuenta o usar Rootwise, usted acepta estos Términos y la legislación aplicable. Si no está de acuerdo, no utilice el servicio.'] },
      { title: '3. Cuentas y elegibilidad', paragraphs: ['Usted es responsable de la exactitud de su cuenta y de su seguridad. No debe suplantar a otras personas ni usar la plataforma con fines ilegales o abusivos.'] },
      { title: '4. Uso permitido', paragraphs: ['Usted se compromete a no publicar contenido dañino, ilegal, infractor o abusivo; no intentar accesos no autorizados; y no interferir con la integridad o disponibilidad de la plataforma ni con otros usuarios.'] },
      { title: '5. Contenido del usuario', paragraphs: ['Usted conserva la titularidad del contenido que suba. Al publicarlo, otorga a Rootwise una licencia limitada para alojarlo, mostrarlo y procesarlo para operar la plataforma.'] },
      { title: '6. Funciones de pago y facturación', paragraphs: ['Algunas funciones están disponibles mediante planes de pago. La facturación, renovaciones y cancelaciones se gestionan mediante el flujo de pago mostrado en la aplicación.'] },
      { title: '7. Suspensión y terminación', paragraphs: ['Podemos suspender o terminar cuentas que infrinjan estos Términos, dañen a usuarios o generen riesgos legales o de seguridad.'] },
      { title: '8. Descargo y responsabilidad', paragraphs: ['El servicio se proporciona "tal cual" y según disponibilidad. En la máxima medida permitida por la ley, EventNexus OÜ no será responsable por daños indirectos o consecuentes.'] },
      { title: '9. Cambios de los términos', paragraphs: ['Podemos actualizar estos Términos periódicamente. Las versiones actualizadas entran en vigor al publicarse y mostrarán la fecha de actualización en esta página.'] },
      { title: '10. Contacto', paragraphs: ['Las consultas sobre estos Términos pueden enviarse a villu@mail.eventnexus.eu. Tiempo de respuesta habitual: dentro de 24 horas.'] },
    ],
  },
  fr: {
    updated: 'Dernière mise à jour : 15 février 2026',
    sections: [
      { title: '1. Exploitant', paragraphs: ['Rootwise est exploité par EventNexus OÜ (n° d’enregistrement 17431557), Põltsamaa, Estonie.', 'Contact : villu@mail.eventnexus.eu', 'Site web : www.eventnexus.eu'] },
      { title: '2. Acceptation des conditions', paragraphs: ['En créant un compte ou en utilisant Rootwise, vous acceptez les présentes Conditions et les lois applicables. Si vous n’êtes pas d’accord, n’utilisez pas le service.'] },
      { title: '3. Comptes et éligibilité', paragraphs: ['Vous êtes responsable de l’exactitude des informations de compte et de la sécurité de votre compte. L’usurpation d’identité et l’utilisation illégale ou abusive sont interdites.'] },
      { title: '4. Utilisation acceptable', paragraphs: ['Vous vous engagez à ne pas publier de contenu nuisible, illégal, contrefaisant ou abusif, à ne pas tenter d’accès non autorisé et à ne pas perturber l’intégrité ou la disponibilité de la plateforme ni les autres utilisateurs.'] },
      { title: '5. Contenu utilisateur', paragraphs: ['Vous conservez la propriété du contenu que vous mettez en ligne. En publiant ce contenu, vous accordez à Rootwise une licence limitée pour l’héberger, l’afficher et le traiter afin d’exploiter la plateforme.'] },
      { title: '6. Fonctions payantes et facturation', paragraphs: ['Certaines fonctionnalités sont disponibles via des offres payantes. La facturation, les renouvellements et les annulations sont gérés via le parcours de paiement affiché dans l’application.'] },
      { title: '7. Suspension et résiliation', paragraphs: ['Nous pouvons suspendre ou résilier les comptes qui enfreignent ces Conditions, nuisent aux utilisateurs ou créent des risques juridiques ou de sécurité.'] },
      { title: '8. Exclusion de garantie et responsabilité', paragraphs: ['Le service est fourni "en l’état" et "selon disponibilité". Dans les limites autorisées par la loi, EventNexus OÜ n’est pas responsable des dommages indirects ou consécutifs.'] },
      { title: '9. Modifications des conditions', paragraphs: ['Nous pouvons mettre à jour ces Conditions de temps à autre. Les versions mises à jour prennent effet lors de leur publication, avec la date de mise à jour indiquée sur cette page.'] },
      { title: '10. Contact', paragraphs: ['Les questions concernant ces Conditions peuvent être envoyées à villu@mail.eventnexus.eu. Délai de réponse habituel : sous 24 heures.'] },
    ],
  },
  it: {
    updated: 'Ultimo aggiornamento: 15 febbraio 2026',
    sections: [
      { title: '1. Gestore', paragraphs: ['Rootwise è gestito da EventNexus OÜ (n. di registrazione 17431557), Põltsamaa, Estonia.', 'Contatto: villu@mail.eventnexus.eu', 'Sito web: www.eventnexus.eu'] },
      { title: '2. Accettazione dei termini', paragraphs: ['Creando un account o utilizzando Rootwise, Lei accetta i presenti Termini e le leggi applicabili. Se non è d’accordo, non utilizzi il servizio.'] },
      { title: '3. Account e requisiti', paragraphs: ['Lei è responsabile della correttezza dei dati dell’account e della sua sicurezza. È vietato impersonare altre persone o usare la piattaforma per scopi illeciti o abusivi.'] },
      { title: '4. Uso consentito', paragraphs: ['Lei si impegna a non pubblicare contenuti dannosi, illegali, lesivi o abusivi; a non tentare accessi non autorizzati; e a non interferire con l’integrità o la disponibilità della piattaforma o con altri utenti.'] },
      { title: '5. Contenuti dell’utente', paragraphs: ['Lei mantiene la proprietà dei contenuti caricati. Pubblicando contenuti, concede a Rootwise una licenza limitata per ospitarli, mostrarli e trattarli ai fini dell’operatività della piattaforma.'] },
      { title: '6. Funzionalità a pagamento e fatturazione', paragraphs: ['Alcune funzionalità sono disponibili tramite piani a pagamento. Fatturazione, rinnovi e cancellazioni sono gestiti tramite il flusso di pagamento mostrato nell’app.'] },
      { title: '7. Sospensione e risoluzione', paragraphs: ['Possiamo sospendere o chiudere account che violano questi Termini, danneggiano gli utenti o creano rischi legali o di sicurezza.'] },
      { title: '8. Esclusione di garanzia e responsabilità', paragraphs: ['Il servizio è fornito "così com’è" e "secondo disponibilità". Nella misura massima consentita dalla legge, EventNexus OÜ non è responsabile per danni indiretti o consequenziali.'] },
      { title: '9. Modifiche ai termini', paragraphs: ['Possiamo aggiornare periodicamente questi Termini. Le versioni aggiornate diventano efficaci alla pubblicazione, con data aggiornata indicata in questa pagina.'] },
      { title: '10. Contatto', paragraphs: ['Per domande su questi Termini, scriva a villu@mail.eventnexus.eu. Tempo di risposta tipico: entro 24 ore.'] },
    ],
  },
  lv: {
    updated: 'Pēdējoreiz atjaunināts: 2026. gada 15. februārī',
    sections: [
      { title: '1. Operators', paragraphs: ['Rootwise uztur EventNexus OÜ (reģ. nr. 17431557), Põltsamaa, Igaunija.', 'Kontakts: villu@mail.eventnexus.eu', 'Mājaslapa: www.eventnexus.eu'] },
      { title: '2. Noteikumu pieņemšana', paragraphs: ['Izveidojot kontu vai izmantojot Rootwise, Jūs piekrītat šiem Noteikumiem un piemērojamiem tiesību aktiem. Ja nepiekrītat, lūdzu, neizmantojiet pakalpojumu.'] },
      { title: '3. Konti un atbilstība', paragraphs: ['Jūs esat atbildīgs par konta datu pareizību un konta drošību. Ir aizliegts uzdoties par citu personu vai izmantot platformu nelikumīgiem vai ļaunprātīgiem mērķiem.'] },
      { title: '4. Atļautā lietošana', paragraphs: ['Jūs piekrītat nepublicēt kaitīgu, nelikumīgu, tiesības pārkāpjošu vai aizskarošu saturu, nemēģināt nesankcionētu piekļuvi un netraucēt platformas darbību vai citu lietotāju pieredzi.'] },
      { title: '5. Lietotāja saturs', paragraphs: ['Jūs saglabājat īpašumtiesības uz augšupielādēto saturu. Publicējot saturu, Jūs piešķirat Rootwise ierobežotu licenci to mitināt, attēlot un apstrādāt platformas darbības nodrošināšanai.'] },
      { title: '6. Maksas funkcijas un norēķini', paragraphs: ['Dažas funkcijas ir pieejamas maksas plānos. Rēķini, atjaunošana un atcelšana tiek pārvaldīti ar lietotnē redzamo maksājumu plūsmu.'] },
      { title: '7. Apturēšana un izbeigšana', paragraphs: ['Mēs varam apturēt vai slēgt kontus, kas pārkāpj šos Noteikumus, kaitē lietotājiem vai rada drošības vai juridiskus riskus.'] },
      { title: '8. Atruna un atbildība', paragraphs: ['Pakalpojums tiek sniegts "kā ir" un "kā pieejams". Maksimālajā apmērā, ko pieļauj likums, EventNexus OÜ neatbild par netiešiem vai izrietošiem zaudējumiem.'] },
      { title: '9. Noteikumu izmaiņas', paragraphs: ['Mēs periodiski varam atjaunināt šos Noteikumus. Atjauninātās versijas stājas spēkā publicēšanas brīdī, un šajā lapā tiek norādīts atjaunināšanas datums.'] },
      { title: '10. Kontakti', paragraphs: ['Jautājumus par šiem Noteikumiem sūtiet uz villu@mail.eventnexus.eu. Parastais atbildes laiks: 24 stundu laikā.'] },
    ],
  },
  lt: {
    updated: 'Paskutinį kartą atnaujinta: 2026 m. vasario 15 d.',
    sections: [
      { title: '1. Valdytojas', paragraphs: ['Rootwise valdo EventNexus OÜ (reg. nr. 17431557), Põltsamaa, Estija.', 'Kontaktai: villu@mail.eventnexus.eu', 'Svetainė: www.eventnexus.eu'] },
      { title: '2. Sąlygų priėmimas', paragraphs: ['Sukurdami paskyrą arba naudodamiesi Rootwise, Jūs sutinkate su šiomis Sąlygomis ir taikomais teisės aktais. Jei nesutinkate, paslaugos nenaudokite.'] },
      { title: '3. Paskyros ir tinkamumas', paragraphs: ['Jūs atsakote už paskyros duomenų tikslumą ir paskyros saugumą. Draudžiama apsimetinėti kitais asmenimis arba naudoti platformą neteisėtais ar piktnaudžiaujančiais tikslais.'] },
      { title: '4. Leidžiamas naudojimas', paragraphs: ['Jūs įsipareigojate neskelbti žalingo, neteisėto, teises pažeidžiančio ar įžeidžiančio turinio, nebandyti neteisėtos prieigos ir netrikdyti platformos veikimo ar kitų naudotojų.'] },
      { title: '5. Naudotojo turinys', paragraphs: ['Jūs išlaikote nuosavybės teises į įkeltą turinį. Skelbdami turinį suteikiate Rootwise ribotą licenciją jį talpinti, rodyti ir tvarkyti platformos veikimui užtikrinti.'] },
      { title: '6. Mokamos funkcijos ir atsiskaitymas', paragraphs: ['Kai kurios funkcijos prieinamos mokamuose planuose. Atsiskaitymas, pratęsimas ir atšaukimas valdomi per programoje rodomą mokėjimo eigą.'] },
      { title: '7. Sustabdymas ir nutraukimas', paragraphs: ['Galime sustabdyti arba nutraukti paskyras, kurios pažeidžia šias Sąlygas, kenkia naudotojams arba kelia saugumo ar teisinę riziką.'] },
      { title: '8. Atsakomybės ribojimas', paragraphs: ['Paslauga teikiama „tokia, kokia yra“ ir „pagal prieinamumą“. Kiek leidžia įstatymai, EventNexus OÜ neatsako už netiesioginę ar pasekminę žalą.'] },
      { title: '9. Sąlygų pakeitimai', paragraphs: ['Kartais galime atnaujinti šias Sąlygas. Atnaujintos versijos įsigalioja paskelbimo momentu, o atnaujinimo data nurodoma šiame puslapyje.'] },
      { title: '10. Kontaktai', paragraphs: ['Klausimus dėl šių Sąlygų siųskite adresu villu@mail.eventnexus.eu. Įprastas atsakymo laikas: per 24 valandas.'] },
    ],
  },
  nl: {
    updated: 'Laatst bijgewerkt: 15 februari 2026',
    sections: [
      { title: '1. Exploitant', paragraphs: ['Rootwise wordt beheerd door EventNexus OÜ (reg.nr. 17431557), Põltsamaa, Estland.', 'Contact: villu@mail.eventnexus.eu', 'Website: www.eventnexus.eu'] },
      { title: '2. Aanvaarding van de voorwaarden', paragraphs: ['Door een account aan te maken of Rootwise te gebruiken, gaat u akkoord met deze Voorwaarden en toepasselijke wetgeving. Als u niet akkoord gaat, gebruik de dienst dan niet.'] },
      { title: '3. Accounts en geschiktheid', paragraphs: ['U bent verantwoordelijk voor de juistheid van uw accountgegevens en voor de beveiliging van uw account. U mag zich niet voordoen als iemand anders en de dienst niet onwettig of misbruikend gebruiken.'] },
      { title: '4. Toegestaan gebruik', paragraphs: ['U stemt ermee in geen schadelijke, illegale, inbreukmakende of misbruikende inhoud te plaatsen, geen ongeautoriseerde toegang te proberen en de integriteit of beschikbaarheid van het platform of andere gebruikers niet te verstoren.'] },
      { title: '5. Gebruikersinhoud', paragraphs: ['U behoudt eigendom van de inhoud die u uploadt. Door inhoud te plaatsen, verleent u Rootwise een beperkte licentie om die inhoud te hosten, weer te geven en te verwerken voor de werking van het platform.'] },
      { title: '6. Betaalde functies en facturering', paragraphs: ['Sommige functionaliteiten zijn beschikbaar via betaalde plannen. Facturering, verlengingen en annuleringen worden beheerd via de betaalstroom die in de app wordt getoond.'] },
      { title: '7. Opschorting en beëindiging', paragraphs: ['Wij kunnen accounts opschorten of beëindigen die deze Voorwaarden schenden, gebruikers schaden of beveiligings- of juridische risico’s veroorzaken.'] },
      { title: '8. Disclaimer en aansprakelijkheid', paragraphs: ['De dienst wordt geleverd "zoals deze is" en "zoals beschikbaar". Voor zover wettelijk toegestaan, is EventNexus OÜ niet aansprakelijk voor indirecte of gevolgschade.'] },
      { title: '9. Wijzigingen in de voorwaarden', paragraphs: ['Wij kunnen deze Voorwaarden van tijd tot tijd bijwerken. Bijgewerkte versies worden van kracht bij publicatie, met de bijgewerkte datum op deze pagina.'] },
      { title: '10. Contact', paragraphs: ['Vragen over deze Voorwaarden kunt u sturen naar villu@mail.eventnexus.eu. Gebruikelijke reactietijd: binnen 24 uur.'] },
    ],
  },
  pl: {
    updated: 'Ostatnia aktualizacja: 15 lutego 2026',
    sections: [
      { title: '1. Operator', paragraphs: ['Rootwise jest obsługiwane przez EventNexus OÜ (nr rejestracyjny 17431557), Põltsamaa, Estonia.', 'Kontakt: villu@mail.eventnexus.eu', 'Strona: www.eventnexus.eu'] },
      { title: '2. Akceptacja warunków', paragraphs: ['Tworząc konto lub korzystając z Rootwise, zgadza się Pan/Pani na niniejsze Warunki i obowiązujące przepisy. Jeśli Pan/Pani nie akceptuje warunków, prosimy nie korzystać z usługi.'] },
      { title: '3. Konta i uprawnienia', paragraphs: ['Użytkownik odpowiada za poprawność danych konta i bezpieczeństwo konta. Zabronione jest podszywanie się pod inne osoby oraz używanie platformy do celów niezgodnych z prawem lub nadużyć.'] },
      { title: '4. Dozwolone korzystanie', paragraphs: ['Użytkownik zobowiązuje się nie publikować treści szkodliwych, nielegalnych, naruszających prawa lub obraźliwych, nie próbować nieautoryzowanego dostępu oraz nie zakłócać działania platformy ani innych użytkowników.'] },
      { title: '5. Treści użytkownika', paragraphs: ['Użytkownik zachowuje własność przesłanych treści. Publikując treści, udziela Rootwise ograniczonej licencji na ich hostowanie, wyświetlanie i przetwarzanie na potrzeby działania platformy.'] },
      { title: '6. Funkcje płatne i rozliczenia', paragraphs: ['Niektóre funkcje są dostępne w płatnych planach. Rozliczenia, odnowienia i anulacje są realizowane przez przepływ płatności widoczny w aplikacji.'] },
      { title: '7. Zawieszenie i zakończenie', paragraphs: ['Możemy zawiesić lub zamknąć konta naruszające te Warunki, szkodzące użytkownikom lub stwarzające ryzyko bezpieczeństwa lub ryzyko prawne.'] },
      { title: '8. Zastrzeżenie i odpowiedzialność', paragraphs: ['Usługa jest świadczona „w stanie, w jakim jest” i „zgodnie z dostępnością”. W maksymalnym zakresie dozwolonym przez prawo EventNexus OÜ nie ponosi odpowiedzialności za szkody pośrednie lub następcze.'] },
      { title: '9. Zmiany warunków', paragraphs: ['Możemy okresowo aktualizować te Warunki. Zaktualizowane wersje obowiązują od chwili publikacji, a data aktualizacji jest wskazana na tej stronie.'] },
      { title: '10. Kontakt', paragraphs: ['Pytania dotyczące tych Warunków można kierować na adres villu@mail.eventnexus.eu. Typowy czas odpowiedzi: do 24 godzin.'] },
    ],
  },
  pt: {
    updated: 'Última atualização: 15 de fevereiro de 2026',
    sections: [
      { title: '1. Operador', paragraphs: ['A Rootwise é operada pela EventNexus OÜ (n.º de registo 17431557), Põltsamaa, Estónia.', 'Contacto: villu@mail.eventnexus.eu', 'Website: www.eventnexus.eu'] },
      { title: '2. Aceitação dos termos', paragraphs: ['Ao criar uma conta ou utilizar a Rootwise, aceita estes Termos e a legislação aplicável. Se não concordar, não utilize o serviço.'] },
      { title: '3. Contas e elegibilidade', paragraphs: ['É responsável pela exatidão dos dados da conta e pela segurança da mesma. Não deve fazer-se passar por terceiros nem utilizar a plataforma para fins ilegais ou abusivos.'] },
      { title: '4. Utilização aceitável', paragraphs: ['Concorda em não publicar conteúdo nocivo, ilegal, infrator ou abusivo; não tentar acesso não autorizado; e não interferir com a integridade ou disponibilidade da plataforma ou com outros utilizadores.'] },
      { title: '5. Conteúdo do utilizador', paragraphs: ['Mantém a propriedade do conteúdo que carrega. Ao publicar conteúdo, concede à Rootwise uma licença limitada para alojar, apresentar e processar esse conteúdo para operar a plataforma.'] },
      { title: '6. Funcionalidades pagas e faturação', paragraphs: ['Algumas funcionalidades estão disponíveis em planos pagos. A faturação, renovações e cancelamentos são geridos através do fluxo de pagamento apresentado na aplicação.'] },
      { title: '7. Suspensão e cessação', paragraphs: ['Podemos suspender ou encerrar contas que violem estes Termos, prejudiquem utilizadores ou criem riscos legais ou de segurança.'] },
      { title: '8. Isenção e responsabilidade', paragraphs: ['O serviço é fornecido "tal como está" e "conforme disponível". Na máxima medida permitida por lei, a EventNexus OÜ não é responsável por danos indiretos ou consequenciais.'] },
      { title: '9. Alterações aos termos', paragraphs: ['Podemos atualizar estes Termos periodicamente. As versões atualizadas entram em vigor após publicação, com a data de atualização indicada nesta página.'] },
      { title: '10. Contacto', paragraphs: ['Questões sobre estes Termos podem ser enviadas para villu@mail.eventnexus.eu. Tempo típico de resposta: até 24 horas.'] },
    ],
  },
  fi: {
    updated: 'Viimeksi päivitetty: 15. helmikuuta 2026',
    sections: [
      { title: '1. Palvelun tarjoaja', paragraphs: ['Rootwise-palvelua ylläpitää EventNexus OÜ (rekisterinumero 17431557), Põltsamaa, Viro.', 'Yhteys: villu@mail.eventnexus.eu', 'Verkkosivu: www.eventnexus.eu'] },
      { title: '2. Ehtojen hyväksyminen', paragraphs: ['Luomalla tilin tai käyttämällä Rootwisea hyväksytte nämä ehdot ja sovellettavan lainsäädännön. Jos ette hyväksy ehtoja, älkää käyttäkö palvelua.'] },
      { title: '3. Tilit ja kelpoisuus', paragraphs: ['Vastaatte tilitietojen oikeellisuudesta ja tilin turvallisuudesta. Toisten henkilöiden esiintyminen tai palvelun lainvastainen tai väärinkäyttävä käyttö on kielletty.'] },
      { title: '4. Hyväksyttävä käyttö', paragraphs: ['Sitoudutte olemaan julkaisematta haitallista, laitonta, oikeuksia loukkaavaa tai väärinkäyttävää sisältöä, olemaan yrittämättä luvatonta pääsyä sekä olemaan häiritsemättä alustan toimintaa tai muita käyttäjiä.'] },
      { title: '5. Käyttäjän sisältö', paragraphs: ['Säilytätte omistusoikeuden lataamaanne sisältöön. Julkaisemalla sisältöä annatte Rootwiselle rajatun lisenssin sisällön ylläpitämiseen, näyttämiseen ja käsittelyyn alustan toiminnan mahdollistamiseksi.'] },
      { title: '6. Maksulliset ominaisuudet ja laskutus', paragraphs: ['Osa ominaisuuksista on saatavilla maksullisissa suunnitelmissa. Laskutus, uusinta ja peruutus hoidetaan sovelluksessa näkyvän maksuprosessin kautta.'] },
      { title: '7. Keskeytys ja päättäminen', paragraphs: ['Voimme keskeyttää tai lopettaa tilit, jotka rikkovat näitä ehtoja, vahingoittavat käyttäjiä tai aiheuttavat turvallisuus- tai oikeudellisia riskejä.'] },
      { title: '8. Vastuunrajoitus', paragraphs: ['Palvelu tarjotaan "sellaisena kuin se on" ja "saatavuuden mukaan". Lain sallimissa rajoissa EventNexus OÜ ei vastaa välillisistä tai seurannaisvahingoista.'] },
      { title: '9. Ehtojen muutokset', paragraphs: ['Voimme päivittää näitä ehtoja ajoittain. Päivitetyt versiot tulevat voimaan julkaisuhetkellä, ja päivityspäivä näkyy tällä sivulla.'] },
      { title: '10. Yhteystiedot', paragraphs: ['Kysymykset näistä ehdoista voi lähettää osoitteeseen villu@mail.eventnexus.eu. Tyypillinen vastausaika: 24 tunnin kuluessa.'] },
    ],
  },
  sv: {
    updated: 'Senast uppdaterad: 15 februari 2026',
    sections: [
      { title: '1. Operatör', paragraphs: ['Rootwise drivs av EventNexus OÜ (registreringsnr 17431557), Põltsamaa, Estland.', 'Kontakt: villu@mail.eventnexus.eu', 'Webbplats: www.eventnexus.eu'] },
      { title: '2. Godkännande av villkor', paragraphs: ['Genom att skapa ett konto eller använda Rootwise godkänner Ni dessa villkor och tillämplig lagstiftning. Om Ni inte samtycker ska Ni inte använda tjänsten.'] },
      { title: '3. Konton och behörighet', paragraphs: ['Ni ansvarar för att kontouppgifter är korrekta och för kontots säkerhet. Det är förbjudet att utge sig för att vara någon annan eller använda plattformen för olagliga eller missbrukande ändamål.'] },
      { title: '4. Tillåten användning', paragraphs: ['Ni förbinder Er att inte publicera skadligt, olagligt, intrångsgörande eller kränkande innehåll, inte försöka få obehörig åtkomst och inte störa plattformens integritet, tillgänglighet eller andra användare.'] },
      { title: '5. Användarinnehåll', paragraphs: ['Ni behåller äganderätten till innehåll som Ni laddar upp. Genom att publicera innehåll ger Ni Rootwise en begränsad licens att lagra, visa och behandla innehållet för att driva plattformen.'] },
      { title: '6. Betalda funktioner och fakturering', paragraphs: ['Vissa funktioner finns i betalplaner. Fakturering, förnyelser och uppsägningar hanteras via betalflödet som visas i appen.'] },
      { title: '7. Avstängning och uppsägning', paragraphs: ['Vi kan stänga av eller avsluta konton som bryter mot dessa villkor, skadar användare eller skapar säkerhets- eller juridiska risker.'] },
      { title: '8. Ansvarsfriskrivning och ansvar', paragraphs: ['Tjänsten tillhandahålls "i befintligt skick" och "i mån av tillgänglighet". I den utsträckning lagen medger ansvarar EventNexus OÜ inte för indirekta eller följdskador.'] },
      { title: '9. Ändringar av villkor', paragraphs: ['Vi kan uppdatera dessa villkor då och då. Uppdaterade versioner gäller från publicering, och uppdateringsdatum visas på denna sida.'] },
      { title: '10. Kontakt', paragraphs: ['Frågor om dessa villkor kan skickas till villu@mail.eventnexus.eu. Normal svarstid: inom 24 timmar.'] },
    ],
  },
  uk: {
    updated: 'Останнє оновлення: 15 лютого 2026 року',
    sections: [
      { title: '1. Оператор', paragraphs: ['Rootwise управляється компанією EventNexus OÜ (реєстраційний № 17431557), Пильтсамаа, Естонія.', 'Контакт: villu@mail.eventnexus.eu', 'Вебсайт: www.eventnexus.eu'] },
      { title: '2. Прийняття умов', paragraphs: ['Створюючи обліковий запис або користуючись Rootwise, Ви погоджуєтеся з цими Умовами та застосовним законодавством. Якщо Ви не погоджуєтеся, не використовуйте сервіс.'] },
      { title: '3. Облікові записи та відповідність', paragraphs: ['Ви несете відповідальність за точність даних облікового запису та його безпеку. Заборонено видавати себе за інших осіб або використовувати платформу для незаконних чи зловживальних цілей.'] },
      { title: '4. Дозволене використання', paragraphs: ['Ви зобов’язуєтеся не публікувати шкідливий, незаконний, такий, що порушує права, або образливий контент; не намагатися отримати несанкціонований доступ; і не порушувати цілісність або доступність платформи чи роботу інших користувачів.'] },
      { title: '5. Контент користувача', paragraphs: ['Ви зберігаєте право власності на завантажений контент. Публікуючи контент, Ви надаєте Rootwise обмежену ліцензію на розміщення, відображення та обробку цього контенту для роботи платформи.'] },
      { title: '6. Платні функції та оплата', paragraphs: ['Деякі функції доступні у платних планах. Оплата, продовження та скасування керуються через платіжний процес, показаний у застосунку.'] },
      { title: '7. Призупинення та припинення', paragraphs: ['Ми можемо призупинити або припинити облікові записи, які порушують ці Умови, шкодять користувачам або створюють юридичні чи безпекові ризики.'] },
      { title: '8. Відмова від гарантій і відповідальність', paragraphs: ['Сервіс надається "як є" та "за наявністю". У максимально дозволеному законом обсязі EventNexus OÜ не несе відповідальності за непрямі або наслідкові збитки.'] },
      { title: '9. Зміни умов', paragraphs: ['Ми можемо періодично оновлювати ці Умови. Оновлені версії набирають чинності з моменту публікації, а дата оновлення зазначається на цій сторінці.'] },
      { title: '10. Контакт', paragraphs: ['Питання щодо цих Умов можна надсилати на villu@mail.eventnexus.eu. Типовий час відповіді: протягом 24 годин.'] },
    ],
  },
  ru: {
    updated: 'Последнее обновление: 15 февраля 2026',
    sections: [
      { title: '1. Оператор', paragraphs: ['Rootwise управляется компанией EventNexus OÜ (рег. № 17431557), Пылтсамаа, Эстония.', 'Контакт: villu@mail.eventnexus.eu', 'Сайт: www.eventnexus.eu'] },
      { title: '2. Принятие условий', paragraphs: ['Создавая аккаунт или используя Rootwise, Вы соглашаетесь с этими Условиями и применимым законодательством. Если Вы не согласны, не используйте сервис.'] },
      { title: '3. Аккаунты и допуск', paragraphs: ['Вы отвечаете за точность данных аккаунта и безопасность аккаунта. Запрещено выдавать себя за других лиц и использовать платформу в незаконных или злоупотребляющих целях.'] },
      { title: '4. Допустимое использование', paragraphs: ['Вы соглашаетесь не публиковать вредоносный, незаконный, нарушающий права или оскорбительный контент; не пытаться получить несанкционированный доступ; и не нарушать целостность или доступность платформы либо работу других пользователей.'] },
      { title: '5. Пользовательский контент', paragraphs: ['Вы сохраняете право собственности на загружаемый контент. Публикуя контент, Вы предоставляете Rootwise ограниченную лицензию на хранение, отображение и обработку контента для работы платформы.'] },
      { title: '6. Платные функции и оплата', paragraphs: ['Некоторые функции доступны в платных планах. Оплата, продление и отмена управляются через платёжный поток, отображаемый в приложении.'] },
      { title: '7. Приостановка и прекращение', paragraphs: ['Мы можем приостановить или прекратить доступ к аккаунтам, нарушающим эти Условия, причиняющим вред пользователям или создающим юридические/безопасностные риски.'] },
      { title: '8. Отказ от гарантий и ответственность', paragraphs: ['Сервис предоставляется "как есть" и "по мере доступности". В максимально допустимой законом степени EventNexus OÜ не несёт ответственности за косвенные или последующие убытки.'] },
      { title: '9. Изменения условий', paragraphs: ['Мы можем периодически обновлять эти Условия. Обновлённые версии вступают в силу с момента публикации, дата обновления указывается на этой странице.'] },
      { title: '10. Контакты', paragraphs: ['Вопросы по этим Условиям можно отправлять на villu@mail.eventnexus.eu. Обычное время ответа: в течение 24 часов.'] },
    ],
  },
};

export const PRIVACY_CONTENT: Record<LegalLocale, LegalDoc> = {
  en: {
    updated: 'Last updated: February 15, 2026',
    sections: [
      { title: '1. Data Controller', paragraphs: ['EventNexus OÜ (reg. no. 17431557), Põltsamaa, Estonia, operates Rootwise and is the data controller for personal data processed through this platform.', 'Contact: villu@mail.eventnexus.eu', 'Website: www.eventnexus.eu'] },
      { title: '2. What We Collect', paragraphs: ['We may process account details (name, email), profile information (age range, interests, skills, avatar), platform activity (quests, messages, community interactions), and technical data needed for security and service reliability.'] },
      { title: '3. Why We Process Data', paragraphs: ['We process personal data to provide the service, maintain account access, enable social and community features, improve product quality, prevent abuse, and meet legal obligations.'] },
      { title: '4. Legal Basis', paragraphs: ['Processing is based on contract performance (providing the platform), legitimate interest (security, product improvement), consent where required, and compliance with applicable law.'] },
      { title: '5. Sharing & Processors', paragraphs: ['We use trusted service providers (such as hosting, analytics, and payment infrastructure) that process data on our behalf under appropriate safeguards. We do not sell personal data.'] },
      { title: '6. Data Retention', paragraphs: ['We keep data only as long as needed for service delivery, legal compliance, dispute resolution, and legitimate business needs. Retention periods may differ by data type.'] },
      { title: '7. Your Rights', paragraphs: ['You may request access, correction, deletion, restriction, or portability of personal data, and object to certain processing where applicable. You may also lodge a complaint with your local supervisory authority.'] },
      { title: '8. Security', paragraphs: ['We apply technical and organizational measures to protect data. No online system is 100% secure, but we continuously improve safeguards and incident response processes.'] },
      { title: '9. Contact', paragraphs: ['For privacy requests and questions, email villu@mail.eventnexus.eu. Typical response time: within 24 hours.'] },
    ],
  },
  et: {
    updated: 'Viimati uuendatud: 15. veebruar 2026',
    sections: [
      { title: '1. Vastutav töötleja', paragraphs: ['EventNexus OÜ (reg. nr 17431557), Põltsamaa, Eesti, haldab Rootwise’i ning on selle platvormi kaudu töödeldavate isikuandmete vastutav töötleja.', 'Kontakt: villu@mail.eventnexus.eu', 'Veeb: www.eventnexus.eu'] },
      { title: '2. Milliseid andmeid kogume', paragraphs: ['Võime töödelda kontoandmeid (nimi, e-post), profiiliinfot (vanusevahemik, huvid, oskused, avatar), platvormi tegevusi (ülesanded, sõnumid, kogukonnasuhtlus) ning tehnilisi andmeid, mis on vajalikud turvalisuse ja teenuse töökindluse jaoks.'] },
      { title: '3. Miks andmeid töötleme', paragraphs: ['Töötleme isikuandmeid teenuse pakkumiseks, konto ligipääsu haldamiseks, kogukonnafunktsioonide võimaldamiseks, tootekvaliteedi parandamiseks, kuritarvituste ennetamiseks ja seadusest tulenevate kohustuste täitmiseks.'] },
      { title: '4. Õiguslik alus', paragraphs: ['Töötlemine põhineb lepingu täitmisel (platvormi pakkumine), õigustatud huvil (turvalisus, tootearendus), nõusolekul (kui vajalik) ja kohaldatava õiguse järgimisel.'] },
      { title: '5. Jagamine ja töötlejad', paragraphs: ['Kasutame usaldusväärseid teenusepakkujaid (nt hostimine, analüütika ja makseinfrastruktuur), kes töötlevad andmeid meie nimel asjakohaste kaitsemeetmete alusel. Me ei müü isikuandmeid.'] },
      { title: '6. Säilitamine', paragraphs: ['Säilitame andmeid ainult nii kaua, kui see on vajalik teenuse osutamiseks, seaduslike kohustuste täitmiseks, vaidluste lahendamiseks ja õigustatud ärihuvide kaitseks. Tähtajad võivad andmeliigiti erineda.'] },
      { title: '7. Sinu õigused', paragraphs: ['Sul on õigus taotleda ligipääsu, parandamist, kustutamist, töötlemise piiramist või andmete ülekandmist ning teatud juhtudel esitada vastuväiteid. Samuti võid pöörduda oma kohaliku järelevalveasutuse poole.'] },
      { title: '8. Turvalisus', paragraphs: ['Rakendame tehnilisi ja organisatsioonilisi meetmeid andmete kaitseks. Ükski veebisüsteem ei ole 100% turvaline, kuid täiustame pidevalt kaitsemeetmeid ja intsidentidele reageerimist.'] },
      { title: '9. Kontakt', paragraphs: ['Privaatsusega seotud küsimused ja taotlused saada aadressile villu@mail.eventnexus.eu. Tavapärane vastamisaeg: kuni 24 tundi.'] },
    ],
  },
  de: {
    updated: 'Zuletzt aktualisiert: 15. Februar 2026',
    sections: [
      { title: '1. Verantwortlicher', paragraphs: ['EventNexus OÜ (Reg.-Nr. 17431557), Põltsamaa, Estland, betreibt Rootwise und ist Verantwortlicher für die über diese Plattform verarbeiteten personenbezogenen Daten.', 'Kontakt: villu@mail.eventnexus.eu', 'Webseite: www.eventnexus.eu'] },
      { title: '2. Welche Daten wir erheben', paragraphs: ['Wir können Kontodaten (Name, E-Mail), Profildaten (Altersbereich, Interessen, Fähigkeiten, Avatar), Plattformaktivitäten (Quests, Nachrichten, Community-Interaktionen) sowie technische Daten zur Sicherheit und Zuverlässigkeit des Dienstes verarbeiten.'] },
      { title: '3. Warum wir Daten verarbeiten', paragraphs: ['Wir verarbeiten personenbezogene Daten, um den Dienst bereitzustellen, Kontozugriff zu ermöglichen, soziale und Community-Funktionen bereitzustellen, die Produktqualität zu verbessern, Missbrauch zu verhindern und rechtliche Pflichten zu erfüllen.'] },
      { title: '4. Rechtsgrundlage', paragraphs: ['Die Verarbeitung erfolgt auf Grundlage der Vertragserfüllung (Bereitstellung der Plattform), berechtigter Interessen (Sicherheit, Produktverbesserung), Einwilligung (wo erforderlich) und der Einhaltung geltenden Rechts.'] },
      { title: '5. Weitergabe und Auftragsverarbeiter', paragraphs: ['Wir nutzen vertrauenswürdige Dienstleister (z. B. Hosting, Analyse und Zahlungsinfrastruktur), die Daten in unserem Auftrag unter angemessenen Schutzmaßnahmen verarbeiten. Wir verkaufen keine personenbezogenen Daten.'] },
      { title: '6. Speicherdauer', paragraphs: ['Wir speichern Daten nur so lange, wie es für die Leistungserbringung, gesetzliche Pflichten, Streitbeilegung und berechtigte Geschäftsinteressen erforderlich ist. Die Fristen können je Datentyp variieren.'] },
      { title: '7. Ihre Rechte', paragraphs: ['Sie können Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragbarkeit Ihrer Daten verlangen und in bestimmten Fällen Widerspruch einlegen. Sie können außerdem bei Ihrer zuständigen Aufsichtsbehörde Beschwerde einreichen.'] },
      { title: '8. Sicherheit', paragraphs: ['Wir setzen technische und organisatorische Maßnahmen zum Schutz von Daten ein. Kein Onlinesystem ist zu 100 % sicher, aber wir verbessern fortlaufend Schutzmaßnahmen und Reaktionsprozesse.'] },
      { title: '9. Kontakt', paragraphs: ['Bei Datenschutzanfragen wenden Sie sich an villu@mail.eventnexus.eu. Übliche Antwortzeit: innerhalb von 24 Stunden.'] },
    ],
  },
  es: {
    updated: 'Última actualización: 15 de febrero de 2026',
    sections: [
      { title: '1. Responsable del tratamiento', paragraphs: ['EventNexus OÜ (n.º de registro 17431557), Põltsamaa, Estonia, opera Rootwise y es responsable del tratamiento de los datos personales procesados a través de esta plataforma.', 'Contacto: villu@mail.eventnexus.eu', 'Sitio web: www.eventnexus.eu'] },
      { title: '2. Qué recopilamos', paragraphs: ['Podemos tratar datos de cuenta (nombre, correo), información de perfil (rango de edad, intereses, habilidades, avatar), actividad de la plataforma (misiones, mensajes, interacciones de comunidad) y datos técnicos necesarios para seguridad y fiabilidad.'] },
      { title: '3. Por qué tratamos datos', paragraphs: ['Tratamos datos personales para prestar el servicio, mantener el acceso a cuentas, habilitar funciones sociales y comunitarias, mejorar la calidad del producto, prevenir abusos y cumplir obligaciones legales.'] },
      { title: '4. Base jurídica', paragraphs: ['El tratamiento se basa en la ejecución del contrato (prestación de la plataforma), interés legítimo (seguridad y mejora del producto), consentimiento cuando sea necesario y cumplimiento de la legislación aplicable.'] },
      { title: '5. Cesión y encargados', paragraphs: ['Utilizamos proveedores de confianza (como hosting, analítica e infraestructura de pagos) que tratan datos por nuestra cuenta con garantías adecuadas. No vendemos datos personales.'] },
      { title: '6. Conservación de datos', paragraphs: ['Conservamos los datos solo durante el tiempo necesario para prestar el servicio, cumplir obligaciones legales, resolver disputas y proteger intereses empresariales legítimos. Los plazos pueden variar por tipo de dato.'] },
      { title: '7. Sus derechos', paragraphs: ['Puede solicitar acceso, rectificación, eliminación, limitación o portabilidad de sus datos, y oponerse a ciertos tratamientos cuando proceda. También puede presentar reclamación ante su autoridad de control local.'] },
      { title: '8. Seguridad', paragraphs: ['Aplicamos medidas técnicas y organizativas para proteger los datos. Ningún sistema en línea es 100 % seguro, pero mejoramos continuamente nuestras salvaguardas y procesos de respuesta.'] },
      { title: '9. Contacto', paragraphs: ['Para solicitudes de privacidad, escriba a villu@mail.eventnexus.eu. Tiempo de respuesta habitual: dentro de 24 horas.'] },
    ],
  },
  fr: {
    updated: 'Dernière mise à jour : 15 février 2026',
    sections: [
      { title: '1. Responsable du traitement', paragraphs: ['EventNexus OÜ (n° d’enregistrement 17431557), Põltsamaa, Estonie, exploite Rootwise et est responsable du traitement des données personnelles via cette plateforme.', 'Contact : villu@mail.eventnexus.eu', 'Site web : www.eventnexus.eu'] },
      { title: '2. Données collectées', paragraphs: ['Nous pouvons traiter les données de compte (nom, e-mail), les informations de profil (tranche d’âge, centres d’intérêt, compétences, avatar), l’activité sur la plateforme (quêtes, messages, interactions communautaires) et des données techniques nécessaires à la sécurité et à la fiabilité du service.'] },
      { title: '3. Pourquoi nous traitons les données', paragraphs: ['Nous traitons les données personnelles pour fournir le service, maintenir l’accès au compte, activer les fonctionnalités sociales et communautaires, améliorer la qualité du produit, prévenir les abus et respecter nos obligations légales.'] },
      { title: '4. Base légale', paragraphs: ['Le traitement repose sur l’exécution du contrat (fourniture de la plateforme), l’intérêt légitime (sécurité et amélioration du produit), le consentement lorsque requis et le respect de la loi applicable.'] },
      { title: '5. Partage et sous-traitants', paragraphs: ['Nous faisons appel à des prestataires de confiance (hébergement, analytique, infrastructure de paiement) qui traitent des données en notre nom avec des garanties appropriées. Nous ne vendons pas de données personnelles.'] },
      { title: '6. Durée de conservation', paragraphs: ['Nous conservons les données uniquement pendant la durée nécessaire à la fourniture du service, au respect des obligations légales, à la résolution des litiges et à la protection des intérêts légitimes. Les durées varient selon le type de données.'] },
      { title: '7. Vos droits', paragraphs: ['Vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité de vos données, et vous opposer à certains traitements lorsque cela s’applique. Vous pouvez également déposer une réclamation auprès de votre autorité de contrôle locale.'] },
      { title: '8. Sécurité', paragraphs: ['Nous appliquons des mesures techniques et organisationnelles pour protéger les données. Aucun système en ligne n’est sûr à 100 %, mais nous améliorons en continu nos protections et nos processus de réponse.'] },
      { title: '9. Contact', paragraphs: ['Pour toute demande liée à la vie privée, écrivez à villu@mail.eventnexus.eu. Délai de réponse habituel : sous 24 heures.'] },
    ],
  },
  it: {
    updated: 'Ultimo aggiornamento: 15 febbraio 2026',
    sections: [
      { title: '1. Titolare del trattamento', paragraphs: ['EventNexus OÜ (n. di registrazione 17431557), Põltsamaa, Estonia, gestisce Rootwise ed è il titolare del trattamento dei dati personali trattati tramite questa piattaforma.', 'Contatto: villu@mail.eventnexus.eu', 'Sito web: www.eventnexus.eu'] },
      { title: '2. Cosa raccogliamo', paragraphs: ['Possiamo trattare dati dell’account (nome, email), informazioni del profilo (fascia d’età, interessi, competenze, avatar), attività sulla piattaforma (missioni, messaggi, interazioni nella community) e dati tecnici necessari per sicurezza e affidabilità del servizio.'] },
      { title: '3. Perché trattiamo i dati', paragraphs: ['Trattiamo i dati personali per fornire il servizio, mantenere l’accesso all’account, abilitare funzionalità social e di community, migliorare la qualità del prodotto, prevenire abusi e adempiere agli obblighi legali.'] },
      { title: '4. Base giuridica', paragraphs: ['Il trattamento si basa sull’esecuzione del contratto (fornitura della piattaforma), sul legittimo interesse (sicurezza e miglioramento del prodotto), sul consenso quando necessario e sul rispetto della legge applicabile.'] },
      { title: '5. Condivisione e responsabili del trattamento', paragraphs: ['Utilizziamo fornitori affidabili (hosting, analisi e infrastruttura di pagamento) che trattano i dati per nostro conto con adeguate garanzie. Non vendiamo dati personali.'] },
      { title: '6. Conservazione dei dati', paragraphs: ['Conserviamo i dati solo per il tempo necessario all’erogazione del servizio, alla conformità legale, alla risoluzione delle controversie e alla tutela di legittimi interessi aziendali. I periodi possono variare in base al tipo di dato.'] },
      { title: '7. I Suoi diritti', paragraphs: ['Può richiedere accesso, rettifica, cancellazione, limitazione o portabilità dei dati personali e opporsi a determinati trattamenti quando applicabile. Può anche presentare reclamo all’autorità di controllo locale.'] },
      { title: '8. Sicurezza', paragraphs: ['Applichiamo misure tecniche e organizzative per proteggere i dati. Nessun sistema online è sicuro al 100%, ma miglioriamo continuamente le salvaguardie e i processi di risposta agli incidenti.'] },
      { title: '9. Contatto', paragraphs: ['Per richieste relative alla privacy, scriva a villu@mail.eventnexus.eu. Tempo di risposta tipico: entro 24 ore.'] },
    ],
  },
  lv: {
    updated: 'Pēdējoreiz atjaunināts: 2026. gada 15. februārī',
    sections: [
      { title: '1. Datu pārzinis', paragraphs: ['EventNexus OÜ (reģ. nr. 17431557), Põltsamaa, Igaunija, uztur Rootwise un ir datu pārzinis personas datiem, kas tiek apstrādāti šajā platformā.', 'Kontakts: villu@mail.eventnexus.eu', 'Mājaslapa: www.eventnexus.eu'] },
      { title: '2. Ko mēs vācam', paragraphs: ['Mēs varam apstrādāt konta datus (vārds, e-pasts), profila informāciju (vecuma grupa, intereses, prasmes, avatārs), platformas aktivitāti (uzdevumi, ziņas, kopienas mijiedarbība) un tehniskos datus drošībai un pakalpojuma uzticamībai.'] },
      { title: '3. Kāpēc mēs apstrādājam datus', paragraphs: ['Mēs apstrādājam personas datus, lai nodrošinātu pakalpojumu, uzturētu piekļuvi kontam, nodrošinātu sociālās un kopienas funkcijas, uzlabotu produktu, novērstu ļaunprātīgu izmantošanu un izpildītu juridiskās saistības.'] },
      { title: '4. Juridiskais pamats', paragraphs: ['Apstrāde balstās uz līguma izpildi (platformas nodrošināšana), leģitīmajām interesēm (drošība, produkta uzlabošana), piekrišanu, ja nepieciešams, un piemērojamo tiesību aktu ievērošanu.'] },
      { title: '5. Kopīgošana un apstrādātāji', paragraphs: ['Mēs izmantojam uzticamus pakalpojumu sniedzējus (piem., hostings, analītika, maksājumu infrastruktūra), kas apstrādā datus mūsu vārdā ar atbilstošiem aizsardzības pasākumiem. Mēs nepārdodam personas datus.'] },
      { title: '6. Datu glabāšana', paragraphs: ['Mēs glabājam datus tikai tik ilgi, cik nepieciešams pakalpojuma sniegšanai, juridisko pienākumu izpildei, strīdu risināšanai un leģitīmo biznesa interešu nodrošināšanai. Glabāšanas termiņi var atšķirties pēc datu veida.'] },
      { title: '7. Jūsu tiesības', paragraphs: ['Jūs varat pieprasīt piekļuvi, labošanu, dzēšanu, apstrādes ierobežošanu vai datu pārnesamību, kā arī noteiktos gadījumos iebilst pret apstrādi. Jūs varat iesniegt sūdzību arī vietējā uzraudzības iestādē.'] },
      { title: '8. Drošība', paragraphs: ['Mēs ieviešam tehniskus un organizatoriskus pasākumus datu aizsardzībai. Neviena tiešsaistes sistēma nav 100% droša, tomēr mēs nepārtraukti uzlabojam aizsardzību un reaģēšanas procesus.'] },
      { title: '9. Kontakti', paragraphs: ['Privātuma pieprasījumus un jautājumus sūtiet uz villu@mail.eventnexus.eu. Parastais atbildes laiks: 24 stundu laikā.'] },
    ],
  },
  lt: {
    updated: 'Paskutinį kartą atnaujinta: 2026 m. vasario 15 d.',
    sections: [
      { title: '1. Duomenų valdytojas', paragraphs: ['EventNexus OÜ (reg. nr. 17431557), Põltsamaa, Estija, valdo Rootwise ir yra asmens duomenų, tvarkomų per šią platformą, valdytojas.', 'Kontaktai: villu@mail.eventnexus.eu', 'Svetainė: www.eventnexus.eu'] },
      { title: '2. Ką renkame', paragraphs: ['Galime tvarkyti paskyros duomenis (vardas, el. paštas), profilio informaciją (amžiaus grupė, interesai, įgūdžiai, avataras), platformos veiklą (užduotys, žinutės, bendruomenės sąveikos) ir techninius duomenis, reikalingus saugumui ir patikimumui.'] },
      { title: '3. Kodėl tvarkome duomenis', paragraphs: ['Asmens duomenis tvarkome tam, kad teiktume paslaugą, užtikrintume paskyros prieigą, socialines ir bendruomenės funkcijas, gerintume produkto kokybę, užkirstume kelią piktnaudžiavimui ir vykdytume teisinius įsipareigojimus.'] },
      { title: '4. Teisinis pagrindas', paragraphs: ['Tvarkymas grindžiamas sutarties vykdymu (platformos teikimas), teisėtu interesu (saugumas, produkto tobulinimas), sutikimu, kai to reikia, ir taikytinos teisės laikymusi.'] },
      { title: '5. Dalijimasis ir tvarkytojai', paragraphs: ['Naudojame patikimus paslaugų teikėjus (pvz., talpinimą, analitiką, mokėjimų infrastruktūrą), kurie tvarko duomenis mūsų vardu taikydami tinkamas apsaugos priemones. Mes neparduodame asmens duomenų.'] },
      { title: '6. Duomenų saugojimas', paragraphs: ['Duomenis saugome tik tiek, kiek būtina paslaugai teikti, teisės aktų reikalavimams vykdyti, ginčams spręsti ir teisėtiems verslo interesams užtikrinti. Terminai gali skirtis pagal duomenų tipą.'] },
      { title: '7. Jūsų teisės', paragraphs: ['Galite prašyti prieigos, taisymo, ištrynimo, tvarkymo apribojimo ar duomenų perkeliamumo ir tam tikrais atvejais nesutikti su tvarkymu. Taip pat galite pateikti skundą savo vietos priežiūros institucijai.'] },
      { title: '8. Saugumas', paragraphs: ['Taikome technines ir organizacines priemones duomenims apsaugoti. Nė viena internetinė sistema nėra 100% saugi, tačiau nuolat tobuliname apsaugos ir reagavimo į incidentus procesus.'] },
      { title: '9. Kontaktai', paragraphs: ['Privatumo klausimus ir prašymus siųskite adresu villu@mail.eventnexus.eu. Įprastas atsakymo laikas: per 24 valandas.'] },
    ],
  },
  nl: {
    updated: 'Laatst bijgewerkt: 15 februari 2026',
    sections: [
      { title: '1. Verwerkingsverantwoordelijke', paragraphs: ['EventNexus OÜ (reg.nr. 17431557), Põltsamaa, Estland, exploiteert Rootwise en is verwerkingsverantwoordelijke voor persoonsgegevens die via dit platform worden verwerkt.', 'Contact: villu@mail.eventnexus.eu', 'Website: www.eventnexus.eu'] },
      { title: '2. Wat wij verzamelen', paragraphs: ['Wij kunnen accountgegevens verwerken (naam, e-mail), profielinformatie (leeftijdscategorie, interesses, vaardigheden, avatar), platformactiviteit (quests, berichten, community-interacties) en technische gegevens voor beveiliging en betrouwbaarheid.'] },
      { title: '3. Waarom wij gegevens verwerken', paragraphs: ['Wij verwerken persoonsgegevens om de dienst te leveren, accounttoegang te onderhouden, sociale en community-functies te bieden, de productkwaliteit te verbeteren, misbruik te voorkomen en aan wettelijke verplichtingen te voldoen.'] },
      { title: '4. Rechtsgrond', paragraphs: ['Verwerking is gebaseerd op uitvoering van de overeenkomst (levering van het platform), gerechtvaardigd belang (beveiliging en productverbetering), toestemming waar vereist en naleving van toepasselijke wetgeving.'] },
      { title: '5. Delen en verwerkers', paragraphs: ['Wij gebruiken vertrouwde dienstverleners (zoals hosting, analytics en betaalinfrastructuur) die gegevens namens ons verwerken met passende waarborgen. Wij verkopen geen persoonsgegevens.'] },
      { title: '6. Bewaartermijn', paragraphs: ['Wij bewaren gegevens alleen zolang als nodig is voor dienstverlening, wettelijke naleving, geschillenbeslechting en legitieme bedrijfsbelangen. Bewaartermijnen kunnen per gegevenstype verschillen.'] },
      { title: '7. Uw rechten', paragraphs: ['U kunt inzage, correctie, verwijdering, beperking of overdraagbaarheid van persoonsgegevens aanvragen en in bepaalde gevallen bezwaar maken tegen verwerking. U kunt ook een klacht indienen bij uw lokale toezichthouder.'] },
      { title: '8. Beveiliging', paragraphs: ['Wij nemen technische en organisatorische maatregelen om gegevens te beschermen. Geen enkel online systeem is 100% veilig, maar wij verbeteren onze beveiliging en responsprocessen voortdurend.'] },
      { title: '9. Contact', paragraphs: ['Voor privacyverzoeken en vragen kunt u mailen naar villu@mail.eventnexus.eu. Gebruikelijke reactietijd: binnen 24 uur.'] },
    ],
  },
  pl: {
    updated: 'Ostatnia aktualizacja: 15 lutego 2026',
    sections: [
      { title: '1. Administrator danych', paragraphs: ['EventNexus OÜ (nr rejestracyjny 17431557), Põltsamaa, Estonia, prowadzi Rootwise i jest administratorem danych osobowych przetwarzanych za pośrednictwem tej platformy.', 'Kontakt: villu@mail.eventnexus.eu', 'Strona: www.eventnexus.eu'] },
      { title: '2. Jakie dane zbieramy', paragraphs: ['Możemy przetwarzać dane konta (imię i nazwisko, e-mail), informacje profilowe (przedział wiekowy, zainteresowania, umiejętności, avatar), aktywność na platformie (misje, wiadomości, interakcje społeczności) oraz dane techniczne potrzebne do bezpieczeństwa i niezawodności.'] },
      { title: '3. Dlaczego przetwarzamy dane', paragraphs: ['Przetwarzamy dane osobowe, aby świadczyć usługę, utrzymywać dostęp do konta, umożliwiać funkcje społecznościowe, poprawiać jakość produktu, zapobiegać nadużyciom i spełniać obowiązki prawne.'] },
      { title: '4. Podstawa prawna', paragraphs: ['Przetwarzanie opiera się na wykonaniu umowy (świadczenie platformy), prawnie uzasadnionym interesie (bezpieczeństwo, rozwój produktu), zgodzie — gdy jest wymagana — oraz zgodności z obowiązującym prawem.'] },
      { title: '5. Udostępnianie i podmioty przetwarzające', paragraphs: ['Korzystamy ze sprawdzonych dostawców (np. hosting, analityka, infrastruktura płatności), którzy przetwarzają dane w naszym imieniu z odpowiednimi zabezpieczeniami. Nie sprzedajemy danych osobowych.'] },
      { title: '6. Przechowywanie danych', paragraphs: ['Przechowujemy dane tylko tak długo, jak to niezbędne do świadczenia usługi, zgodności prawnej, rozwiązywania sporów i ochrony uzasadnionych interesów biznesowych. Okresy mogą się różnić zależnie od rodzaju danych.'] },
      { title: '7. Państwa prawa', paragraphs: ['Mogą Państwo żądać dostępu, sprostowania, usunięcia, ograniczenia lub przenoszenia danych oraz sprzeciwić się określonemu przetwarzaniu, gdy ma to zastosowanie. Mogą też Państwo złożyć skargę do lokalnego organu nadzorczego.'] },
      { title: '8. Bezpieczeństwo', paragraphs: ['Stosujemy środki techniczne i organizacyjne w celu ochrony danych. Żaden system online nie jest w 100% bezpieczny, ale stale ulepszamy zabezpieczenia i procesy reagowania.'] },
      { title: '9. Kontakt', paragraphs: ['Wnioski i pytania dotyczące prywatności prosimy kierować na villu@mail.eventnexus.eu. Typowy czas odpowiedzi: do 24 godzin.'] },
    ],
  },
  pt: {
    updated: 'Última atualização: 15 de fevereiro de 2026',
    sections: [
      { title: '1. Responsável pelo tratamento', paragraphs: ['A EventNexus OÜ (n.º de registo 17431557), Põltsamaa, Estónia, opera a Rootwise e é a responsável pelo tratamento dos dados pessoais processados através desta plataforma.', 'Contacto: villu@mail.eventnexus.eu', 'Website: www.eventnexus.eu'] },
      { title: '2. O que recolhemos', paragraphs: ['Podemos processar dados da conta (nome, e-mail), informações de perfil (faixa etária, interesses, competências, avatar), atividade na plataforma (missões, mensagens, interações da comunidade) e dados técnicos necessários para segurança e fiabilidade.'] },
      { title: '3. Porque processamos dados', paragraphs: ['Processamos dados pessoais para prestar o serviço, manter o acesso à conta, permitir funcionalidades sociais e de comunidade, melhorar a qualidade do produto, prevenir abusos e cumprir obrigações legais.'] },
      { title: '4. Base legal', paragraphs: ['O tratamento baseia-se na execução do contrato (prestação da plataforma), interesse legítimo (segurança e melhoria do produto), consentimento quando necessário e cumprimento da legislação aplicável.'] },
      { title: '5. Partilha e subcontratantes', paragraphs: ['Utilizamos prestadores de confiança (como alojamento, analítica e infraestrutura de pagamentos) que processam dados em nosso nome com salvaguardas adequadas. Não vendemos dados pessoais.'] },
      { title: '6. Retenção de dados', paragraphs: ['Mantemos os dados apenas pelo tempo necessário para prestação do serviço, cumprimento legal, resolução de litígios e interesses empresariais legítimos. Os prazos podem variar por tipo de dado.'] },
      { title: '7. Os seus direitos', paragraphs: ['Pode solicitar acesso, retificação, eliminação, limitação ou portabilidade dos dados pessoais e opor-se a certos tratamentos quando aplicável. Pode também apresentar reclamação junto da autoridade de supervisão local.'] },
      { title: '8. Segurança', paragraphs: ['Aplicamos medidas técnicas e organizacionais para proteger os dados. Nenhum sistema online é 100% seguro, mas melhoramos continuamente as salvaguardas e os processos de resposta.'] },
      { title: '9. Contacto', paragraphs: ['Para pedidos e questões de privacidade, contacte villu@mail.eventnexus.eu. Tempo típico de resposta: até 24 horas.'] },
    ],
  },
  fi: {
    updated: 'Viimeksi päivitetty: 15. helmikuuta 2026',
    sections: [
      { title: '1. Rekisterinpitäjä', paragraphs: ['EventNexus OÜ (rekisterinumero 17431557), Põltsamaa, Viro, ylläpitää Rootwisea ja toimii tämän alustan kautta käsiteltävien henkilötietojen rekisterinpitäjänä.', 'Yhteys: villu@mail.eventnexus.eu', 'Verkkosivu: www.eventnexus.eu'] },
      { title: '2. Mitä keräämme', paragraphs: ['Voimme käsitellä tilitietoja (nimi, sähköposti), profiilitietoja (ikäryhmä, kiinnostuksenkohteet, taidot, avatar), alustatoimintaa (tehtävät, viestit, yhteisövuorovaikutus) ja teknisiä tietoja turvallisuuden ja luotettavuuden varmistamiseksi.'] },
      { title: '3. Miksi käsittelemme tietoja', paragraphs: ['Käsittelemme henkilötietoja palvelun tarjoamiseksi, tilin käytön ylläpitämiseksi, sosiaalisten ja yhteisöominaisuuksien mahdollistamiseksi, tuotteen laadun parantamiseksi, väärinkäytösten estämiseksi ja lakisääteisten velvoitteiden täyttämiseksi.'] },
      { title: '4. Oikeusperuste', paragraphs: ['Käsittely perustuu sopimuksen täytäntöönpanoon (alustan tarjoaminen), oikeutettuun etuun (turvallisuus ja tuotteen kehitys), suostumukseen tarvittaessa sekä soveltuvan lainsäädännön noudattamiseen.'] },
      { title: '5. Jakaminen ja käsittelijät', paragraphs: ['Käytämme luotettuja palveluntarjoajia (kuten hosting, analytiikka ja maksuinfrastruktuuri), jotka käsittelevät tietoja puolestamme asianmukaisin suojatoimin. Emme myy henkilötietoja.'] },
      { title: '6. Tietojen säilytys', paragraphs: ['Säilytämme tietoja vain niin kauan kuin on tarpeen palvelun toimittamiseen, lakisääteisten velvoitteiden täyttämiseen, riitojen ratkaisuun ja oikeutettujen liiketoimintaetujen suojaamiseen. Säilytysajat voivat vaihdella tietotyypeittäin.'] },
      { title: '7. Oikeutenne', paragraphs: ['Voitte pyytää pääsyä tietoihin, oikaisua, poistamista, käsittelyn rajoittamista tai siirrettävyyttä sekä vastustaa tiettyä käsittelyä soveltuvin osin. Voitte myös tehdä valituksen paikalliselle valvontaviranomaiselle.'] },
      { title: '8. Tietoturva', paragraphs: ['Käytämme teknisiä ja organisatorisia toimenpiteitä tietojen suojaamiseksi. Mikään verkkopalvelu ei ole 100 % turvallinen, mutta kehitämme jatkuvasti suojauksia ja reagointiprosesseja.'] },
      { title: '9. Yhteystiedot', paragraphs: ['Tietosuojaan liittyvät pyynnöt ja kysymykset voi lähettää osoitteeseen villu@mail.eventnexus.eu. Tyypillinen vastausaika: 24 tunnin kuluessa.'] },
    ],
  },
  sv: {
    updated: 'Senast uppdaterad: 15 februari 2026',
    sections: [
      { title: '1. Personuppgiftsansvarig', paragraphs: ['EventNexus OÜ (registreringsnr 17431557), Põltsamaa, Estland, driver Rootwise och är personuppgiftsansvarig för personuppgifter som behandlas via denna plattform.', 'Kontakt: villu@mail.eventnexus.eu', 'Webbplats: www.eventnexus.eu'] },
      { title: '2. Vad vi samlar in', paragraphs: ['Vi kan behandla kontouppgifter (namn, e-post), profilinformation (åldersgrupp, intressen, färdigheter, avatar), plattformsaktivitet (uppdrag, meddelanden, communityinteraktioner) samt tekniska data som behövs för säkerhet och tillförlitlighet.'] },
      { title: '3. Varför vi behandlar data', paragraphs: ['Vi behandlar personuppgifter för att tillhandahålla tjänsten, upprätthålla kontoåtkomst, möjliggöra sociala och communityfunktioner, förbättra produktkvaliteten, förebygga missbruk och uppfylla rättsliga skyldigheter.'] },
      { title: '4. Rättslig grund', paragraphs: ['Behandlingen grundas på fullgörande av avtal (tillhandahållande av plattformen), berättigat intresse (säkerhet och produktförbättring), samtycke där det krävs samt efterlevnad av tillämplig lag.'] },
      { title: '5. Delning och personuppgiftsbiträden', paragraphs: ['Vi använder betrodda tjänsteleverantörer (t.ex. hosting, analys och betalningsinfrastruktur) som behandlar data för vår räkning med lämpliga skyddsåtgärder. Vi säljer inte personuppgifter.'] },
      { title: '6. Lagring av data', paragraphs: ['Vi behåller data endast så länge som behövs för tjänsteleverans, rättslig efterlevnad, tvistlösning och legitima affärsintressen. Lagringstider kan variera per datatyp.'] },
      { title: '7. Era rättigheter', paragraphs: ['Ni kan begära tillgång, rättelse, radering, begränsning eller dataportabilitet och invända mot viss behandling där det är tillämpligt. Ni kan även lämna klagomål till lokal tillsynsmyndighet.'] },
      { title: '8. Säkerhet', paragraphs: ['Vi använder tekniska och organisatoriska åtgärder för att skydda data. Inget onlinesystem är 100 % säkert, men vi förbättrar kontinuerligt skydd och incidenthantering.'] },
      { title: '9. Kontakt', paragraphs: ['För integritetsärenden och frågor, mejla villu@mail.eventnexus.eu. Normal svarstid: inom 24 timmar.'] },
    ],
  },
  uk: {
    updated: 'Останнє оновлення: 15 лютого 2026 року',
    sections: [
      { title: '1. Контролер даних', paragraphs: ['EventNexus OÜ (реєстраційний № 17431557), Пильтсамаа, Естонія, керує Rootwise та є контролером персональних даних, що обробляються через цю платформу.', 'Контакт: villu@mail.eventnexus.eu', 'Вебсайт: www.eventnexus.eu'] },
      { title: '2. Які дані ми збираємо', paragraphs: ['Ми можемо обробляти дані облікового запису (ім’я, e-mail), дані профілю (вікова група, інтереси, навички, аватар), активність на платформі (квести, повідомлення, взаємодія спільноти) та технічні дані, потрібні для безпеки й надійності.'] },
      { title: '3. Навіщо ми обробляємо дані', paragraphs: ['Ми обробляємо персональні дані для надання сервісу, підтримки доступу до акаунту, забезпечення соціальних і спільнотних функцій, покращення якості продукту, запобігання зловживанням і виконання юридичних обов’язків.'] },
      { title: '4. Правова підстава', paragraphs: ['Обробка базується на виконанні договору (надання платформи), законному інтересі (безпека й покращення продукту), згоді — де це потрібно, та дотриманні застосовного законодавства.'] },
      { title: '5. Передача та обробники', paragraphs: ['Ми використовуємо надійних постачальників послуг (зокрема хостинг, аналітику та платіжну інфраструктуру), які обробляють дані від нашого імені із належними гарантіями. Ми не продаємо персональні дані.'] },
      { title: '6. Зберігання даних', paragraphs: ['Ми зберігаємо дані лише стільки, скільки потрібно для надання послуги, виконання вимог закону, вирішення спорів і захисту законних бізнес-інтересів. Строки можуть відрізнятися залежно від типу даних.'] },
      { title: '7. Ваші права', paragraphs: ['Ви можете вимагати доступ, виправлення, видалення, обмеження обробки або перенесення даних, а також заперечувати проти певної обробки, де це застосовно. Ви також можете подати скаргу до місцевого наглядового органу.'] },
      { title: '8. Безпека', paragraphs: ['Ми застосовуємо технічні та організаційні заходи для захисту даних. Жодна онлайн-система не є захищеною на 100%, але ми постійно покращуємо захист і процеси реагування.'] },
      { title: '9. Контакт', paragraphs: ['З питань приватності звертайтеся на villu@mail.eventnexus.eu. Типовий час відповіді: протягом 24 годин.'] },
    ],
  },
  ru: {
    updated: 'Последнее обновление: 15 февраля 2026',
    sections: [
      { title: '1. Оператор персональных данных', paragraphs: ['EventNexus OÜ (рег. № 17431557), Пылтсамаа, Эстония, управляет Rootwise и является оператором персональных данных, обрабатываемых через эту платформу.', 'Контакт: villu@mail.eventnexus.eu', 'Сайт: www.eventnexus.eu'] },
      { title: '2. Какие данные мы собираем', paragraphs: ['Мы можем обрабатывать данные аккаунта (имя, e-mail), данные профиля (возрастная группа, интересы, навыки, аватар), активность на платформе (квесты, сообщения, взаимодействия в сообществе) и технические данные, необходимые для безопасности и надежности сервиса.'] },
      { title: '3. Зачем мы обрабатываем данные', paragraphs: ['Мы обрабатываем персональные данные для предоставления сервиса, поддержания доступа к аккаунту, работы социальных и community-функций, улучшения качества продукта, предотвращения злоупотреблений и выполнения юридических обязательств.'] },
      { title: '4. Правовое основание', paragraphs: ['Обработка основана на исполнении договора (предоставление платформы), законном интересе (безопасность и развитие продукта), согласии — когда это необходимо, и соблюдении применимого законодательства.'] },
      { title: '5. Передача и обработчики', paragraphs: ['Мы используем надежных поставщиков услуг (например, хостинг, аналитику и платежную инфраструктуру), которые обрабатывают данные от нашего имени при наличии соответствующих гарантий. Мы не продаем персональные данные.'] },
      { title: '6. Срок хранения данных', paragraphs: ['Мы храним данные только столько, сколько необходимо для оказания услуги, соблюдения закона, разрешения споров и защиты законных деловых интересов. Сроки могут отличаться в зависимости от типа данных.'] },
      { title: '7. Ваши права', paragraphs: ['Вы можете запросить доступ, исправление, удаление, ограничение обработки или переносимость персональных данных, а также возражать против определенной обработки, если это применимо. Вы также можете подать жалобу в местный надзорный орган.'] },
      { title: '8. Безопасность', paragraphs: ['Мы применяем технические и организационные меры для защиты данных. Ни одна онлайн-система не является безопасной на 100%, но мы постоянно улучшаем защиту и процессы реагирования.'] },
      { title: '9. Контакты', paragraphs: ['По вопросам приватности пишите на villu@mail.eventnexus.eu. Обычное время ответа: в течение 24 часов.'] },
    ],
  },
};
